name: CD
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  python-packaging:
    name: 🐍 Packaging
    uses: cda-tum/mqt-core/.github/workflows/reusable-python-packaging.yml@main
    with:
      package-name: mqt.qcec
