name: Python

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_COLOR: 3

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  min-qiskit-version:
    name: ⚛️ Min. Qiskit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup nox
        run: pipx install nox
      - name: Run session
        run: nox -s min_qiskit_version -- --cov-report=xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          fail_ci_if_error: true
          flags: python
          token: ${{ secrets.CODECOV_TOKEN }}
